from __future__ import annotations

import os
import uuid
from collections.abc import AsyncIterator
from datetime import UTC, datetime
from typing import Any
from urllib.parse import parse_qsl, urlencode, urlsplit, urlunsplit

import pytest
from langchain_core.runnables import RunnableConfig
from langgraph.graph import END, START, StateGraph
from psycopg import AsyncConnection, sql
from pydantic import SecretStr
from typing_extensions import TypedDict

from ezer.checkpoints import open_checkpointer
from ezer.config import GmailAccount, Settings, StaticTokenAuth
from ezer.domain import EmailAnalysis, EmailEnvelope, SafetyAssessment, SummaryResult
from ezer.persistence import PostgresPersistence

POSTGRES_ENV = "EZER_TEST_POSTGRES_URL"
CHECKPOINT_SENTINEL = "ezer-postgres-encrypted-checkpoint-sentinel"


class _CheckpointState(TypedDict):
    payload: SummaryResult


def _persist_payload(state: _CheckpointState) -> dict[str, SummaryResult]:
    return {"payload": state["payload"]}


def _url_scoped_to_schema(database_url: str, schema: str) -> str:
    parts = urlsplit(database_url)
    if parts.scheme not in {"postgres", "postgresql"} or not parts.netloc:
        raise ValueError(f"{POSTGRES_ENV} must be a PostgreSQL URL")

    query = parse_qsl(parts.query, keep_blank_values=True)
    previous_options = " ".join(value for key, value in query if key == "options")
    query = [(key, value) for key, value in query if key != "options"]
    scoped_options = f"{previous_options} -csearch_path={schema}".strip()
    query.append(("options", scoped_options))
    return urlunsplit(parts._replace(query=urlencode(query)))


@pytest.fixture
async def isolated_postgres_schema() -> AsyncIterator[tuple[str, str]]:
    database_url = os.getenv(POSTGRES_ENV)
    if not database_url:
        pytest.skip(f"set {POSTGRES_ENV} to run the PostgreSQL integration test")

    schema = f"ezer_test_{uuid.uuid4().hex}"
    admin: AsyncConnection[tuple[Any, ...]] = await AsyncConnection.connect(
        database_url,
        autocommit=True,
    )
    try:
        await admin.execute(sql.SQL("CREATE SCHEMA {}").format(sql.Identifier(schema)))
        yield _url_scoped_to_schema(database_url, schema), schema
    finally:
        # The name is generated by this fixture and quoted as one identifier. CASCADE is
        # therefore strictly bounded to this test's private schema.
        await admin.execute(sql.SQL("DROP SCHEMA {} CASCADE").format(sql.Identifier(schema)))
        await admin.close()


def _analysis(claim_id: str, message: EmailEnvelope) -> EmailAnalysis:
    return EmailAnalysis(
        analysis_id=claim_id,
        message_ref=message.message_ref(),
        content_hash=message.content_hash(),
        pipeline_version="postgres-integration-v1",
        model_id="fake-sonnet-5",
        prompt_version="fake-prompts-v1",
        created_at=datetime(2026, 8, 27, tzinfo=UTC),
        category="informational",
        priority="normal",
        needs_human_review=False,
        summary="Résumé PostgreSQL.",
        safety=SafetyAssessment(
            risk_level="none",
            phishing_likelihood=0,
            rationale="No security concern.",
            confidence=1,
        ),
    )


async def test_postgres_persistence_and_encrypted_checkpointer(
    isolated_postgres_schema: tuple[str, str],
) -> None:
    database_url, schema = isolated_postgres_schema
    account = GmailAccount(
        provider="gmail",
        id="postgres-integration",
        auth=StaticTokenAuth(
            type="access_token",
            access_token=SecretStr("test-token"),
        ),
    )
    message = EmailEnvelope(
        account_id=account.id,
        provider="gmail",
        provider_message_id="message-1",
        received_at=datetime(2026, 8, 27, tzinfo=UTC),
        body_text="Bounded PostgreSQL integration payload.",
    )

    persistence = PostgresPersistence(
        database_url,
        min_size=1,
        max_size=2,
        auto_migrate=True,
    )
    await persistence.open()
    try:
        assert await persistence.health() is True
        assert await persistence.set_cursor(account.id, None, "cursor-1") is True
        assert await persistence.set_cursor(account.id, None, "stale") is False
        assert await persistence.set_cursor(account.id, "cursor-1", "cursor-2") is True

        claim = await persistence.claim(
            account,
            message,
            message.content_hash(),
            "postgres-integration-v1",
            60,
            3,
        )
        assert claim is not None
        assert (
            await persistence.claim(
                account,
                message,
                message.content_hash(),
                "postgres-integration-v1",
                60,
                3,
            )
            is None
        )

        expected = _analysis(claim.analysis_id, message)
        await persistence.complete(claim, expected)
        assert await persistence.get_analysis(claim.analysis_id) == expected
    finally:
        await persistence.close()

    settings = Settings.model_validate(
        {
            "checkpoint_database_url": database_url,
            "checkpoint_aes_key": uuid.uuid4().hex,
            "auto_migrate": True,
        }
    )
    builder = StateGraph(_CheckpointState)
    builder.add_node("persist", _persist_payload)
    builder.add_edge(START, "persist")
    builder.add_edge("persist", END)
    config: RunnableConfig = {"configurable": {"thread_id": f"postgres-test-{uuid.uuid4().hex}"}}
    sensitive_result = SummaryResult(
        summary=CHECKPOINT_SENTINEL,
        detected_language="en",
    )

    async with open_checkpointer(settings) as checkpointer:
        graph = builder.compile(checkpointer=checkpointer)
        result = await graph.ainvoke({"payload": sensitive_result}, config)
        snapshot = await graph.aget_state(config)
        assert result["payload"] == sensitive_result
        assert snapshot.values["payload"] == sensitive_result

    verifier: AsyncConnection[tuple[Any, ...]] = await AsyncConnection.connect(
        database_url,
        autocommit=True,
    )
    try:
        table_rows = await (
            await verifier.execute(
                """
                SELECT table_name
                FROM information_schema.tables
                WHERE table_schema = current_schema()
                """
            )
        ).fetchall()
        tables = {str(row[0]) for row in table_rows}
        assert {
            "ezer_sync_cursors",
            "ezer_analysis_runs",
            "checkpoint_migrations",
            "checkpoints",
            "checkpoint_blobs",
            "checkpoint_writes",
        } <= tables

        encrypted_rows = await (
            await verifier.execute(
                """
                SELECT type, blob FROM checkpoint_blobs WHERE blob IS NOT NULL
                UNION ALL
                SELECT type, blob FROM checkpoint_writes WHERE blob IS NOT NULL
                """
            )
        ).fetchall()
        assert encrypted_rows
        assert any(str(row[0]).endswith("+aes") for row in encrypted_rows)
        sentinel = CHECKPOINT_SENTINEL.encode()
        assert all(sentinel not in bytes(row[1]) for row in encrypted_rows)

        checkpoint_rows = await (
            await verifier.execute("SELECT checkpoint::text, metadata::text FROM checkpoints")
        ).fetchall()
        assert CHECKPOINT_SENTINEL not in repr(checkpoint_rows)
        schema_row = await (await verifier.execute("SELECT current_schema()")).fetchone()
        assert schema_row is not None
        assert schema_row[0] == schema
    finally:
        await verifier.close()
